Addition of ClickNCollect resources for export of orders
coopTilleuls/CoopTilleulsSyliusClickNCollectPlugin pull request #21
Opened 2020-04-30 09:16 UTC by flug

2020-05-11 10:35 UTC, dunglas requested changes

2020-05-11 10:35 UTC, dunglas commented on README.md
> +
```suggestion
# config/services.yaml
services:
```

2020-05-11 10:35 UTC, dunglas commented on README.md
> +
```suggestion
# config/services.yaml
services:
```

2020-05-11 10:35 UTC, dunglas commented on README.md
> +
Remove empty lines

2020-05-11 10:35 UTC, dunglas commented on README.md
> +14. Optionally, export commands with ClickNCollect, install this [export library](https://packagist.org/packages/friendsofsylius/sylius-import-export-plugin) and add this :
I would move this in another section.

2020-05-11 10:35 UTC, dunglas commented on src/Exporter/Plugin/OrderResourcePlugin.php
> +class OrderResourcePlugin extends BaseOrderResourcePlugin
```suggestion
final class OrderResourcePlugin extends BaseOrderResourcePlugin
```

2020-05-12 19:34 UTC, toofff approved these changes

2020-05-12 19:36 UTC, merged

2020-05-12 19:36 UTC, toofff commented
Thank's @flug