Functional version php8
coopTilleuls/CoopTilleulsSyliusClickNCollectPlugin pull request #62
Opened 2022-02-28 12:50 UTC by JulieNobody

version fonctionnelle por PHP 8

reste à faire : test

2022-02-28 15:38 UTC, dunglas requested changes
Good job!

The ChromeDriver and Gecko driver binaries must not be committed (add them to `.gitignore`).

2022-02-28 15:38 UTC, dunglas commented on composer.json
>          "symfony/lock": "^4.4 || ^5.0"
Could we also add support for Symfony 6, for all SF dependencies (could be done in another PR)?

2022-02-28 15:38 UTC, dunglas commented on tests/Application/config/packages/doctrine.yaml
> +
```suggestion
```

2023-04-15 09:14 UTC, mathieu-dumoutier commented
Hi!

Have you the intention to finish this PR?

Thank you for your answer

2023-09-29 11:31 UTC, romainallanot commented
closed this as merged in #68

2023-09-29 11:31 UTC, closed without merging